import { Inter } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const h1Font = Inter({ weight: "300", subsets: ["latin"] });
const h2Font = Inter({ weight: "200", subsets: ["latin"] });

const Overlay = () => {
  return (
    <div className="overlay">
      <div className="overlay-top">
        <div className="header">
          <div className="titles">
            <h1 className={`${h1Font.className} tom`}>TOM WALSH</h1>
            <h2 className={`${h2Font.className} designer`}>
              DESIGNER / DEVELOPER
            </h2>
          </div>
          <div className="nav">
            <h2 className={`${h2Font.className} nav-item`}>SERVICES</h2>
            <h2 className={`${h2Font.className} nav-item`}>CONTACT</h2>
            <h2 className={`${h2Font.className} nav-item`}>ABOUT</h2>
          </div>
        </div>
        <hr className="header-rule" />
      </div>
      <div className="overlay-bottom">
        <hr className="footer-rule" />
        <div className="footer">
          <div className="social-links">
            <h2 className={`${h2Font.className} social-links-item`}>
              Instagram
            </h2>
            <h2 className={`${h2Font.className} social-links-item`}>
              LinkedIn
            </h2>
          </div>
          <div className="legal">
            <h2 className={h2Font.className}>
              Designed and Developed by TOM WALSH ⓒ 2025
            </h2>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Overlay;
